##### Import data

In [1]:
from util_copy import load_fabric_data, extract_label_grouping, extract_label_grouping, load_fabric_images
import numpy as np
from matplotlib import image

In [2]:

path = r"C:/Users/Administrator/Desktop/PRML/Project/fabric_data/label_json/**/**.json"

fids, fdata = load_fabric_data(path)
ftype1, ftype2 = extract_label_grouping(fdata)


In [3]:
path = r"C:/Users/Administrator/Desktop/PRML/Project/fabric_data/temp/"
labels, imgs = load_fabric_images(path, fids, fdata, ftype2)


C:/Users/Administrator/Desktop/PRML/Project/fabric_data/temp/**/**.jpg


In [4]:
print(fdata)

[{'flaw_type': 4, 'bbox': {'x0': 125, 'x1': 188, 'y0': 171, 'y1': 230}}, {'flaw_type': 4, 'bbox': {'x0': 79, 'x1': 148, 'y0': 170, 'y1': 231}}, {'flaw_type': 11, 'bbox': {'x0': 145, 'x1': 256, 'y0': 162, 'y1': 238}}, {'flaw_type': 11, 'bbox': {'x0': 145, 'x1': 256, 'y0': 163, 'y1': 238}}, {'flaw_type': 11, 'bbox': {'x0': 165, 'x1': 236, 'y0': 170, 'y1': 230}}, {'flaw_type': 4, 'bbox': {'x0': 41, 'x1': 359, 'y0': 142, 'y1': 259}}, {'flaw_type': 4, 'bbox': {'x0': 250, 'x1': 367, 'y0': 148, 'y1': 253}}, {'flaw_type': 4, 'bbox': {'x0': 127, 'x1': 273, 'y0': 154, 'y1': 247}}, {'flaw_type': 4, 'bbox': {'x0': 128, 'x1': 273, 'y0': 156, 'y1': 245}}, {'flaw_type': 4, 'bbox': {'x0': 129, 'x1': 272, 'y0': 155, 'y1': 246}}, {'flaw_type': 4, 'bbox': {'x0': 116, 'x1': 273, 'y0': 160, 'y1': 241}}, {'flaw_type': 4, 'bbox': {'x0': 143, 'x1': 258, 'y0': 158, 'y1': 243}}, {'flaw_type': 4, 'bbox': {'x0': 147, 'x1': 254, 'y0': 160, 'y1': 240}}, {'flaw_type': 4, 'bbox': {'x0': 0, 'x1': 540, 'y0': 115, 'y1':

In [5]:
print(len(labels))
print(imgs[0])

3371
[[[130 130 128 155 147 171]
  [139 137 138 151 150 168]
  [147 145 148 146 154 167]
  ...
  [ 57  46  24  92  87  29]
  [ 73  51  28  83  64  34]
  [124  89  69  76  47  51]]

 [[139 141 140 162 153 174]
  [143 144 146 157 155 168]
  [148 148 150 151 155 166]
  ...
  [ 69  61  38 121 124  69]
  [ 58  41  15 113 100  56]
  [ 69  39  15  88  63  33]]

 [[143 147 150 160 149 166]
  [145 149 152 156 153 162]
  [150 151 156 153 156 161]
  ...
  [102 100  75 153 160 116]
  [ 90  79  49 140 133  79]
  [ 75  55  22 126 106  47]]

 ...

 [[ 56  19  13  76  21  24]
  [ 55  16  11  77  28  31]
  [ 57  18  13  70  31  32]
  ...
  [208 213 219 210 213 206]
  [208 218 220 222 223 228]
  [200 210 211 216 213 234]]

 [[ 74  35  28 103  31  34]
  [ 69  30  23 103  37  39]
  [ 72  31  25  95  39  40]
  ...
  [191 200 209 212 212 212]
  [220 231 237 209 209 221]
  [196 210 213 213 210 237]]

 [[ 87  49  40 122  36  37]
  [ 82  42  34 123  41  43]
  [ 85  45  37 115  43  46]
  ...
  [185 193 204 214 

In [6]:
n_samples = len(imgs)
print("Number of samples:", n_samples)

Number of samples: 3371


In [7]:
print(imgs[1230].shape)

(400, 400, 6)


##### Padding
- https://blog.csdn.net/wuzqChom/article/details/74785643
- https://stackoverflow.com/questions/47697622/cnn-image-resizing-vs-padding-keeping-aspect-ratio-or-not/49882055#49882055
- https://stackoverflow.com/questions/43391205/add-padding-to-images-to-get-them-into-the-same-shape

In [8]:
import cv2

In [9]:
imgs = [cv2.resize(img,(200, 200)) for img in imgs]

##### Split data

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_images, test_images, train_labels, test_labels = train_test_split(imgs, labels, test_size=0.3, random_state=1)

In [ ]:
print(train_images.type)

In [12]:
print("#Training data: {}\n#Testing data: {}\n#Class: {}".format(len(train_images), len(test_images), len(set(train_labels))))

#Training data: 2359
#Testing data: 1012
#Class: 9


##### Normalize data

In [13]:
train_images, test_images, train_labels, test_labels = np.array(train_images), np.array(test_images), np.array(train_labels), np.array(test_labels)
train_images, test_images = train_images / 255.0, test_images / 255.0

In [14]:
train_images.shape

(2359, 200, 200, 6)

##### Generate fake data

In [17]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import keras,os
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D , Flatten
from keras.preprocessing.image import ImageDataGenerator
import numpy as np


input_shape = (200, 200, 6)

In [21]:

# https://towardsdatascience.com/step-by-step-vgg16-implementation-in-keras-for-beginners-a833c686ae6c


model = Sequential()
model.add(Conv2D(input_shape=input_shape,filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Flatten())
model.add(Dense(units=4096,activation="relu"))
model.add(Dense(units=4096,activation="relu"))
model.add(Dense(units=9, activation="softmax"))

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 200, 200, 64)      3520      
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 200, 200, 64)      36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 100, 100, 64)      0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 100, 100, 128)     73856     
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 100, 100, 128)     147584    
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 50, 50, 128)       0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 50, 50, 256)      

In [ ]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10, 
                    validation_data=(test_images, test_labels))




Epoch 1/10
74/74 [==============================] - ETA: 0s - loss: 2.8353 - accuracy: 0.1780 

##### Create model
- https://www.tensorflow.org/tutorials/images/classification

In [ ]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10, 
                    validation_data=(test_images, test_labels))

##### Testing

In [ ]:
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

In [ ]:
print(test_acc)